application: student-monitor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /student/.*
  script: student.app

- url: /meta/.*
  script: Meta.app
  
- url: /interm/.*
  script: Intermediate.interm

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
